language: python
python:
  - 3.3
install:
  - if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pip install unittest2 --use-mirrors; fi
  - pip install -r tests/requirements.txt
  - pip install -r requirements.txt
script:
  - make test
services: mongodb
