"""add quantity claimed to items

Revision ID: 504b0257562
Revises: 48abe6019f7
Create Date: 2013-11-14 21:58:56.036401

"""

# revision identifiers, used by Alembic.
revision = '504b0257562'
down_revision = '48abe6019f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_items', sa.Column('quantity_claimed', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_items', 'quantity_claimed')
    ### end Alembic commands ###
