"""add name to users

Revision ID: 11a119a067b
Revises: 1ae579134fd
Create Date: 2013-10-31 00:06:17.973286

"""

# revision identifiers, used by Alembic.
revision = '11a119a067b'
down_revision = '1ae579134fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    ### end Alembic commands ###
