"""default passwords to empty strings

Revision ID: 15cfc8761be
Revises: 504b0257562
Create Date: 2014-12-19 12:43:41.080697

"""

# revision identifiers, used by Alembic.
revision = '15cfc8761be'
down_revision = '504b0257562'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

users = table('users', column('password', sa.String))


def upgrade():
    op.execute(
        users.update().where(users.c.password == None).values({'password': ''}))
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=130),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=130),
               nullable=True)
    ### end Alembic commands ###
    op.execute(
        users.update().where(users.c.password == '').values({'password': None}))
