"""add locked to events

Revision ID: 4e82227f9b5
Revises: 11a119a067b
Create Date: 2013-10-31 00:19:03.059147

"""

# revision identifiers, used by Alembic.
revision = '4e82227f9b5'
down_revision = '11a119a067b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('locked', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'locked')
    ### end Alembic commands ###
